import { Difficulty, LeagueInfo, LanguageCode, Team } from './types';

export const LEAGUES: { [key: string]: LeagueInfo } = {
  premier_lig: {
    id: 'premier_lig',
    name: 'Premier League',
    continent: 'Avrupa',
    country: 'İngiltere',
    teams: [
      { id: 'premier_lig_ARS', name: 'Arsenal', abbr: 'ARS', color1: '#EF0107', color2: '#FFFFFF', logo: './assets/logos/premier_lig/ARS.png' },
      { id: 'premier_lig_AVL', name: 'Aston Villa', abbr: 'AVL', color1: '#670E36', color2: '#95BFE5', logo: './assets/logos/premier_lig/AVL.png' },
      { id: 'premier_lig_BOU', name: 'AFC Bournemouth', abbr: 'BOU', color1: '#DA291C', color2: '#000000', logo: './assets/logos/premier_lig/BOU.png' },
      { id: 'premier_lig_BRE', name: 'Brentford', abbr: 'BRE', color1: '#E30613', color2: '#FFFFFF', logo: './assets/logos/premier_lig/BRE.png' },
      { id: 'premier_lig_BHA', name: 'Brighton & Hove Albion', abbr: 'BHA', color1: '#0057B8', color2: '#FFFFFF', logo: './assets/logos/premier_lig/BHA.png' },
      { id: 'premier_lig_CHE', name: 'Chelsea', abbr: 'CHE', color1: '#034694', color2: '#FFFFFF', logo: './assets/logos/premier_lig/CHE.png' },
      { id: 'premier_lig_CRY', name: 'Crystal Palace', abbr: 'CRY', color1: '#1B458F', color2: '#C4122E', logo: './assets/logos/premier_lig/CRY.png' },
      { id: 'premier_lig_EVE', name: 'Everton', abbr: 'EVE', color1: '#003399', color2: '#FFFFFF', logo: './assets/logos/premier_lig/EVE.png' },
      { id: 'premier_lig_FUL', name: 'Fulham', abbr: 'FUL', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/premier_lig/FUL.png' },
      { id: 'premier_lig_IPS', name: 'Ipswich Town', abbr: 'IPS', color1: '#1C53A3', color2: '#FFFFFF', logo: './assets/logos/premier_lig/IPS.png' },
      { id: 'premier_lig_LEI', name: 'Leicester City', abbr: 'LEI', color1: '#003090', color2: '#FFFFFF', logo: './assets/logos/premier_lig/LEI.png' },
      { id: 'premier_lig_LIV', name: 'Liverpool', abbr: 'LIV', color1: '#C8102E', color2: '#FFFFFF', logo: './assets/logos/premier_lig/LIV.png' },
      { id: 'premier_lig_MCI', name: 'Manchester City', abbr: 'MCI', color1: '#6CABDD', color2: '#FFFFFF', logo: './assets/logos/premier_lig/MCI.png' },
      { id: 'premier_lig_MUN', name: 'Manchester United', abbr: 'MUN', color1: '#DA291C', color2: '#FFFFFF', logo: './assets/logos/premier_lig/MUN.png' },
      { id: 'premier_lig_NEW', name: 'Newcastle United', abbr: 'NEW', color1: '#241F20', color2: '#FFFFFF', logo: './assets/logos/premier_lig/NEW.png' },
      { id: 'premier_lig_NFO', name: 'Nottingham Forest', abbr: 'NFO', color1: '#E53233', color2: '#FFFFFF', logo: './assets/logos/premier_lig/NFO.png' },
      { id: 'premier_lig_SOU', name: 'Southampton', abbr: 'SOU', color1: '#D71920', color2: '#FFFFFF', logo: './assets/logos/premier_lig/SOU.png' },
      { id: 'premier_lig_TOT', name: 'Tottenham Hotspur', abbr: 'TOT', color1: '#132257', color2: '#FFFFFF', logo: './assets/logos/premier_lig/TOT.png' },
      { id: 'premier_lig_WHU', name: 'West Ham United', abbr: 'WHU', color1: '#7A263A', color2: '#1BB1E7', logo: './assets/logos/premier_lig/WHU.png' },
      { id: 'premier_lig_WOL', name: 'Wolverhampton Wanderers', abbr: 'WOL', color1: '#FDB913', color2: '#231F20', logo: './assets/logos/premier_lig/WOL.png' },
    ],
  },
  efl_championship: {
    id: 'efl_championship',
    name: 'EFL Championship',
    continent: 'Avrupa',
    country: 'İngiltere',
    teams: [
      { id: 'efl_championship_BLA', name: 'Blackburn Rovers', abbr: 'BLA', color1: '#0057B8', color2: '#FFFFFF', logo: './assets/logos/efl_championship/BLA.png' },
      { id: 'efl_championship_BRI', name: 'Bristol City', abbr: 'BRI', color1: '#E30613', color2: '#FFFFFF', logo: './assets/logos/efl_championship/BRI.png' },
      { id: 'efl_championship_BUR', name: 'Burnley', abbr: 'BUR', color1: '#6C1D45', color2: '#99D6EA', logo: './assets/logos/efl_championship/BUR.png' },
      { id: 'efl_championship_CAR', name: 'Cardiff City', abbr: 'CAR', color1: '#0070B5', color2: '#FFFFFF', logo: './assets/logos/efl_championship/CAR.png' },
      { id: 'efl_championship_COV', name: 'Coventry City', abbr: 'COV', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/efl_championship/COV.png' },
      { id: 'efl_championship_DER', name: 'Derby County', abbr: 'DER', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/efl_championship/DER.png' },
      { id: 'efl_championship_HUL', name: 'Hull City', abbr: 'HUL', color1: '#F5A623', color2: '#000000', logo: './assets/logos/efl_championship/HUL.png' },
      { id: 'efl_championship_LEE', name: 'Leeds United', abbr: 'LEE', color1: '#FFFFFF', color2: '#FFCD00', logo: './assets/logos/efl_championship/LEE.png' },
      { id: 'efl_championship_LUT', name: 'Luton Town', abbr: 'LUT', color1: '#FF6600', color2: '#FFFFFF', logo: './assets/logos/efl_championship/LUT.png' },
      { id: 'efl_championship_MID', name: 'Middlesbrough', abbr: 'MID', color1: '#E30613', color2: '#FFFFFF', logo: './assets/logos/efl_championship/MID.png' },
      { id: 'efl_championship_MIL', name: 'Millwall', abbr: 'MIL', color1: '#003366', color2: '#FFFFFF', logo: './assets/logos/efl_championship/MIL.png' },
      { id: 'efl_championship_NOR', name: 'Norwich City', abbr: 'NOR', color1: '#FFF200', color2: '#00A651', logo: './assets/logos/efl_championship/NOR.png' },
      { id: 'efl_championship_OXF', name: 'Oxford United', abbr: 'OXF', color1: '#FFC425', color2: '#003366', logo: './assets/logos/efl_championship/OXF.png' },
      { id: 'efl_championship_PLY', name: 'Plymouth Argyle', abbr: 'PLY', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/efl_championship/PLY.png' },
      { id: 'efl_championship_POR', name: 'Portsmouth', abbr: 'POR', color1: '#0047AB', color2: '#FFFFFF', logo: './assets/logos/efl_championship/POR.png' },
      { id: 'efl_championship_PNE', name: 'Preston North End', abbr: 'PNE', color1: '#FFFFFF', color2: '#002D62', logo: './assets/logos/efl_championship/PNE.png' },
      { id: 'efl_championship_QPR', name: 'QPR', abbr: 'QPR', color1: '#0057B8', color2: '#FFFFFF', logo: './assets/logos/efl_championship/QPR.png' },
      { id: 'efl_championship_SHU', name: 'Sheffield United', abbr: 'SHU', color1: '#EE2737', color2: '#FFFFFF', logo: './assets/logos/efl_championship/SHU.png' },
      { id: 'efl_championship_SHW', name: 'Sheffield Wednesday', abbr: 'SHW', color1: '#0066CC', color2: '#FFFFFF', logo: './assets/logos/efl_championship/SHW.png' },
      { id: 'efl_championship_STO', name: 'Stoke City', abbr: 'STO', color1: '#E03A3E', color2: '#FFFFFF', logo: './assets/logos/efl_championship/STO.png' },
      { id: 'efl_championship_SUN', name: 'Sunderland', abbr: 'SUN', color1: '#EB172B', color2: '#FFFFFF', logo: './assets/logos/efl_championship/SUN.png' },
      { id: 'efl_championship_SWA', name: 'Swansea City', abbr: 'SWA', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/efl_championship/SWA.png' },
      { id: 'efl_championship_WAT', name: 'Watford', abbr: 'WAT', color1: '#FBEE23', color2: '#ED1C24', logo: './assets/logos/efl_championship/WAT.png' },
      { id: 'efl_championship_WBA', name: 'West Bromwich Albion', abbr: 'WBA', color1: '#002D62', color2: '#FFFFFF', logo: './assets/logos/efl_championship/WBA.png' },
    ],
  },
  la_liga: {
    id: 'la_liga',
    name: 'LALIGA EA SPORTS',
    continent: 'Avrupa',
    country: 'İspanya',
    teams: [
      { id: 'la_liga_ALV', name: 'Deportivo Alavés', abbr: 'ALV', color1: '#0053A4', color2: '#FFFFFF', logo: './assets/logos/la_liga/ALV.png' },
      { id: 'la_liga_ATH', name: 'Athletic Club', abbr: 'ATH', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/la_liga/ATH.png' },
      { id: 'la_liga_ATM', name: 'Atlético de Madrid', abbr: 'ATM', color1: '#CB3524', color2: '#FFFFFF', logo: './assets/logos/la_liga/ATM.png' },
      { id: 'la_liga_BAR', name: 'FC Barcelona', abbr: 'BAR', color1: '#A50044', color2: '#004D98', logo: './assets/logos/la_liga/BAR.png' },
      { id: 'la_liga_BET', name: 'Real Betis', abbr: 'BET', color1: '#00A752', color2: '#FFFFFF', logo: './assets/logos/la_liga/BET.png' },
      { id: 'la_liga_CEL', name: 'Celta de Vigo', abbr: 'CEL', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/la_liga/CEL.png' },
      { id: 'la_liga_ESP', name: 'RCD Espanyol', abbr: 'ESP', color1: '#007FC8', color2: '#FFFFFF', logo: './assets/logos/la_liga/ESP.png' },
      { id: 'la_liga_GET', name: 'Getafe CF', abbr: 'GET', color1: '#0059A5', color2: '#FFFFFF', logo: './assets/logos/la_liga/GET.png' },
      { id: 'la_liga_GIR', name: 'Girona FC', abbr: 'GIR', color1: '#E20A17', color2: '#FFFFFF', logo: './assets/logos/la_liga/GIR.png' },
      { id: 'la_liga_LPA', name: 'UD Las Palmas', abbr: 'LPA', color1: '#FFC400', color2: '#0055A4', logo: './assets/logos/la_liga/LPA.png' },
      { id: 'la_liga_LEG', name: 'CD Leganés', abbr: 'LEG', color1: '#1C3C7E', color2: '#FFFFFF', logo: './assets/logos/la_liga/LEG.png' },
      { id: 'la_liga_MAL', name: 'RCD Mallorca', abbr: 'MAL', color1: '#E20613', color2: '#000000', logo: './assets/logos/la_liga/MAL.png' },
      { id: 'la_liga_OSA', name: 'Osasuna', abbr: 'OSA', color1: '#C8102E', color2: '#002C5F', logo: './assets/logos/la_liga/OSA.png' },
      { id: 'la_liga_RAY', name: 'Rayo Vallecano', abbr: 'RAY', color1: '#FFFFFF', color2: '#D21A28', logo: './assets/logos/la_liga/RAY.png' },
      { id: 'la_liga_RMA', name: 'Real Madrid', abbr: 'RMA', color1: '#FFFFFF', color2: '#FEBE10', logo: './assets/logos/la_liga/RMA.png' },
      { id: 'la_liga_RSO', name: 'Real Sociedad', abbr: 'RSO', color1: '#0067B1', color2: '#FFFFFF', logo: './assets/logos/la_liga/RSO.png' },
      { id: 'la_liga_SEV', name: 'Sevilla FC', abbr: 'SEV', color1: '#FFFFFF', color2: '#D41922', logo: './assets/logos/la_liga/SEV.png' },
      { id: 'la_liga_VAL', name: 'Valencia CF', abbr: 'VAL', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/la_liga/VAL.png' },
      { id: 'la_liga_VLL', name: 'Real Valladolid', abbr: 'VLL', color1: '#5D2483', color2: '#FFFFFF', logo: './assets/logos/la_liga/VLL.png' },
      { id: 'la_liga_VIL', name: 'Villarreal CF', abbr: 'VIL', color1: '#FBEC5D', color2: '#0054A6', logo: './assets/logos/la_liga/VIL.png' },
    ],
  },
   la_liga_2: {
    id: 'la_liga_2',
    name: 'LALIGA HYPERMOTION',
    continent: 'Avrupa',
    country: 'İspanya',
    teams: [
      { id: 'la_liga_2_ALB', name: 'Albacete Balompié', abbr: 'ALB', color1: '#FFFFFF', color2: '#D2122E', logo: './assets/logos/la_liga_2/ALB.png' },
      { id: 'la_liga_2_ALM', name: 'Almería', abbr: 'ALM', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/ALM.png' },
      { id: 'la_liga_2_BUR', name: 'Burgos CF', abbr: 'BUR', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/la_liga_2/BUR.png' },
      { id: 'la_liga_2_CAD', name: 'Cádiz CF', abbr: 'CAD', color1: '#FFC425', color2: '#003366', logo: './assets/logos/la_liga_2/CAD.png' },
      { id: 'la_liga_2_CAR', name: 'FC Cartagena', abbr: 'CAR', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/CAR.png' },
      { id: 'la_liga_2_CAS', name: 'CD Castellón', abbr: 'CAS', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/la_liga_2/CAS.png' },
      { id: 'la_liga_2_DEP', name: 'Deportivo de La Coruña', abbr: 'DEP', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/DEP.png' },
      { id: 'la_liga_2_EIB', name: 'SD Eibar', abbr: 'EIB', color1: '#8A1E2A', color2: '#0055A4', logo: './assets/logos/la_liga_2/EIB.png' },
      { id: 'la_liga_2_ELC', name: 'Elche CF', abbr: 'ELC', color1: '#FFFFFF', color2: '#008000', logo: './assets/logos/la_liga_2/ELC.png' },
      { id: 'la_liga_2_ELD', name: 'CD Eldense', abbr: 'ELD', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/la_liga_2/ELD.png' },
      { id: 'la_liga_2_GRA', name: 'Granada CF', abbr: 'GRA', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/GRA.png' },
      { id: 'la_liga_2_HUE', name: 'SD Huesca', abbr: 'HUE', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/la_liga_2/HUE.png' },
      { id: 'la_liga_2_LEV', name: 'Levante UD', abbr: 'LEV', color1: '#003366', color2: '#ED1C24', logo: './assets/logos/la_liga_2/LEV.png' },
      { id: 'la_liga_2_MLG', name: 'Málaga CF', abbr: 'MLG', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/MLG.png' },
      { id: 'la_liga_2_MIR', name: 'CD Mirandés', abbr: 'MIR', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/la_liga_2/MIR.png' },
      { id: 'la_liga_2_OVI', name: 'Real Oviedo', abbr: 'OVI', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/OVI.png' },
      { id: 'la_liga_2_FER', name: 'Racing de Ferrol', abbr: 'FER', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/FER.png' },
      { id: 'la_liga_2_SAN', name: 'Racing de Santander', abbr: 'SAN', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/SAN.png' },
      { id: 'la_liga_2_SPO', name: 'Sporting de Gijón', abbr: 'SPO', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/SPO.png' },
      { id: 'la_liga_2_TEN', name: 'CD Tenerife', abbr: 'TEN', color1: '#FFFFFF', color2: '#0055A4', logo: './assets/logos/la_liga_2/TEN.png' },
      { id: 'la_liga_2_ZAR', name: 'Real Zaragoza', abbr: 'ZAR', color1: '#FFFFFF', color2: '#0055A4', logo: './assets/logos/la_liga_2/ZAR.png' },
      { id: 'la_liga_2_COR', name: 'Córdoba CF', abbr: 'COR', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/la_liga_2/COR.png' },
    ],
  },
  serie_a: {
    id: 'serie_a',
    name: 'Serie A',
    continent: 'Avrupa',
    country: 'İtalya',
    teams: [
      { id: 'serie_a_ATA', name: 'Atalanta', abbr: 'ATA', color1: '#0068A8', color2: '#000000', logo: './assets/logos/serie_a/ATA.png' },
      { id: 'serie_a_BOL', name: 'Bologna', abbr: 'BOL', color1: '#A71930', color2: '#002F65', logo: './assets/logos/serie_a/BOL.png' },
      { id: 'serie_a_CAG', name: 'Cagliari', abbr: 'CAG', color1: '#DB1527', color2: '#002859', logo: './assets/logos/serie_a/CAG.png' },
      { id: 'serie_a_COM', name: 'Como', abbr: 'COM', color1: '#003882', color2: '#FFFFFF', logo: './assets/logos/serie_a/COM.png' },
      { id: 'serie_a_EMP', name: 'Empoli', abbr: 'EMP', color1: '#005CB9', color2: '#FFFFFF', logo: './assets/logos/serie_a/EMP.png' },
      { id: 'serie_a_FIO', name: 'Fiorentina', abbr: 'FIO', color1: '#482E92', color2: '#FFFFFF', logo: './assets/logos/serie_a/FIO.png' },
      { id: 'serie_a_GEN', name: 'Genoa', abbr: 'GEN', color1: '#AD192D', color2: '#002D5D', logo: './assets/logos/serie_a/GEN.png' },
      { id: 'serie_a_INT', name: 'Inter', abbr: 'INT', color1: '#0068A8', color2: '#000000', logo: './assets/logos/serie_a/INT.png' },
      { id: 'serie_a_JUV', name: 'Juventus', abbr: 'JUV', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/serie_a/JUV.png' },
      { id: 'serie_a_LAZ', name: 'Lazio', abbr: 'LAZ', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/serie_a/LAZ.png' },
      { id: 'serie_a_LEC', name: 'Lecce', abbr: 'LEC', color1: '#FDB913', color2: '#D2122E', logo: './assets/logos/serie_a/LEC.png' },
      { id: 'serie_a_MIL', name: 'AC Milan', abbr: 'MIL', color1: '#FB090B', color2: '#000000', logo: './assets/logos/serie_a/MIL.png' },
      { id: 'serie_a_MNZ', name: 'Monza', abbr: 'MNZ', color1: '#EF242A', color2: '#FFFFFF', logo: './assets/logos/serie_a/MNZ.png' },
      { id: 'serie_a_NAP', name: 'Napoli', abbr: 'NAP', color1: '#12A0D7', color2: '#FFFFFF', logo: './assets/logos/serie_a/NAP.png' },
      { id: 'serie_a_PAR', name: 'Parma', abbr: 'PAR', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/serie_a/PAR.png' },
      { id: 'serie_a_ROM', name: 'AS Roma', abbr: 'ROM', color1: '#970A2C', color2: '#FFC425', logo: './assets/logos/serie_a/ROM.png' },
      { id: 'serie_a_TOR', name: 'Torino', abbr: 'TOR', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/serie_a/TOR.png' },
      { id: 'serie_a_UDI', name: 'Udinese', abbr: 'UDI', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/serie_a/UDI.png' },
      { id: 'serie_a_VEN', name: 'Venezia', abbr: 'VEN', color1: '#000000', color2: '#009639', logo: './assets/logos/serie_a/VEN.png' },
      { id: 'serie_a_VER', name: 'Hellas Verona', abbr: 'VER', color1: '#002D62', color2: '#FFD700', logo: './assets/logos/serie_a/VER.png' },
    ],
  },
  serie_b_it: {
    id: 'serie_b_it',
    name: 'Serie B',
    continent: 'Avrupa',
    country: 'İtalya',
    teams: [
      { id: 'serie_b_it_BAR', name: 'AS Bari', abbr: 'BAR', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/serie_b_it/BAR.png' },
      { id: 'serie_b_it_BRE', name: 'Brescia', abbr: 'BRE', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/serie_b_it/BRE.png' },
      { id: 'serie_b_it_CRR', name: 'Carrarese Calcio 1908', abbr: 'CRR', color1: '#0055A4', color2: '#FFC72C', logo: './assets/logos/serie_b_it/CRR.png' },
      { id: 'serie_b_it_CAT', name: 'Catanzaro', abbr: 'CAT', color1: '#FFC72C', color2: '#ED1C24', logo: './assets/logos/serie_b_it/CAT.png' },
      { id: 'serie_b_it_CES', name: 'Cesena', abbr: 'CES', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/serie_b_it/CES.png' },
      { id: 'serie_b_it_CIT', name: 'Cittadella', abbr: 'CIT', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/serie_b_it/CIT.png' },
      { id: 'serie_b_it_COS', name: 'Cosenza', abbr: 'COS', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/serie_b_it/COS.png' },
      { id: 'serie_b_it_CRE', name: 'Cremonese', abbr: 'CRE', color1: '#ED1C24', color2: '#A9A9A9', logo: './assets/logos/serie_b_it/CRE.png' },
      { id: 'serie_b_it_FRO', name: 'Frosinone', abbr: 'FRO', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/serie_b_it/FRO.png' },
      { id: 'serie_b_it_JVS', name: 'Juve Stabia', abbr: 'JVS', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/serie_b_it/JVS.png' },
      { id: 'serie_b_it_MAN', name: 'Mantova', abbr: 'MAN', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/serie_b_it/MAN.png' },
      { id: 'serie_b_it_MOD', name: 'Modena', abbr: 'MOD', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/serie_b_it/MOD.png' },
      { id: 'serie_b_it_PAL', name: 'Palermo', abbr: 'PAL', color1: '#FFC0CB', color2: '#000000', logo: './assets/logos/serie_b_it/PAL.png' },
      { id: 'serie_b_it_PIS', name: 'Pisa', abbr: 'PIS', color1: '#000000', color2: '#0055A4', logo: './assets/logos/serie_b_it/PIS.png' },
      { id: 'serie_b_it_REG', name: 'Reggiana', abbr: 'REG', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/serie_b_it/REG.png' },
      { id: 'serie_b_it_SAL', name: 'Salernitana', abbr: 'SAL', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/serie_b_it/SAL.png' },
      { id: 'serie_b_it_SAM', name: 'Sampdoria', abbr: 'SAM', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/serie_b_it/SAM.png' },
      { id: 'serie_b_it_SAS', name: 'Sassuolo', abbr: 'SAS', color1: '#008000', color2: '#000000', logo: './assets/logos/serie_b_it/SAS.png' },
      { id: 'serie_b_it_SPE', name: 'Spezia', abbr: 'SPE', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/serie_b_it/SPE.png' },
      { id: 'serie_b_it_SUD', name: 'Südtirol', abbr: 'SUD', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/serie_b_it/SUD.png' },
    ],
  },
  bundesliga: {
    id: 'bundesliga',
    name: 'Bundesliga',
    continent: 'Avrupa',
    country: 'Almanya',
    teams: [
      { id: 'bundesliga_AUG', name: 'FC Augsburg', abbr: 'AUG', color1: '#FFFFFF', color2: '#BA3733', logo: './assets/logos/bundesliga/AUG.png' },
      { id: 'bundesliga_UNB', name: 'Union Berlin', abbr: 'UNB', color1: '#E20A17', color2: '#FFFFFF', logo: './assets/logos/bundesliga/UNB.png' },
      { id: 'bundesliga_BOC', name: 'VfL Bochum', abbr: 'BOC', color1: '#005CA9', color2: '#FFFFFF', logo: './assets/logos/bundesliga/BOC.png' },
      { id: 'bundesliga_BRE', name: 'Werder Bremen', abbr: 'BRE', color1: '#009647', color2: '#FFFFFF', logo: './assets/logos/bundesliga/BRE.png' },
      { id: 'bundesliga_BVB', name: 'Borussia Dortmund', abbr: 'BVB', color1: '#FDE100', color2: '#000000', logo: './assets/logos/bundesliga/BVB.png' },
      { id: 'bundesliga_SGE', name: 'Eintracht Frankfurt', abbr: 'SGE', color1: '#E1000F', color2: '#000000', logo: './assets/logos/bundesliga/SGE.png' },
      { id: 'bundesliga_FRE', name: 'SC Freiburg', abbr: 'FRE', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/bundesliga/FRE.png' },
      { id: 'bundesliga_HEI', name: 'FC Heidenheim', abbr: 'HEI', color1: '#E60026', color2: '#005BAA', logo: './assets/logos/bundesliga/HEI.png' },
      { id: 'bundesliga_HOF', name: 'TSG Hoffenheim', abbr: 'HOF', color1: '#1C63B7', color2: '#FFFFFF', logo: './assets/logos/bundesliga/HOF.png' },
      { id: 'bundesliga_KIE', name: 'Holstein Kiel', abbr: 'KIE', color1: '#0055A2', color2: '#FFFFFF', logo: './assets/logos/bundesliga/KIE.png' },
      { id: 'bundesliga_RBL', name: 'RB Leipzig', abbr: 'RBL', color1: '#E6002B', color2: '#002E60', logo: './assets/logos/bundesliga/RBL.png' },
      { id: 'bundesliga_LEV', name: 'Bayer 04 Leverkusen', abbr: 'LEV', color1: '#E32221', color2: '#000000', logo: './assets/logos/bundesliga/LEV.png' },
      { id: 'bundesliga_MAI', name: 'Mainz 05', abbr: 'MAI', color1: '#ED1B24', color2: '#FFFFFF', logo: './assets/logos/bundesliga/MAI.png' },
      { id: 'bundesliga_BMG', name: 'Borussia Mönchengladbach', abbr: 'BMG', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/bundesliga/BMG.png' },
      { id: 'bundesliga_BAY', name: 'Bayern München', abbr: 'BAY', color1: '#DC052D', color2: '#FFFFFF', logo: './assets/logos/bundesliga/BAY.png' },
      { id: 'bundesliga_STP', name: 'FC St. Pauli', abbr: 'STP', color1: '#7B4214', color2: '#FFFFFF', logo: './assets/logos/bundesliga/STP.png' },
      { id: 'bundesliga_STU', name: 'VfB Stuttgart', abbr: 'STU', color1: '#FFFFFF', color2: '#E30613', logo: './assets/logos/bundesliga/STU.png' },
      { id: 'bundesliga_WOB', name: 'VfL Wolfsburg', abbr: 'WOB', color1: '#65B32E', color2: '#FFFFFF', logo: './assets/logos/bundesliga/WOB.png' },
    ],
  },
  bundesliga_2: {
    id: 'bundesliga_2',
    name: '2. Bundesliga',
    continent: 'Avrupa',
    country: 'Almanya',
    teams: [
      { id: 'bundesliga_2_BRA', name: 'Eintracht Braunschweig', abbr: 'BRA', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/bundesliga_2/BRA.png' },
      { id: 'bundesliga_2_HER', name: 'Hertha BSC', abbr: 'HER', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/HER.png' },
      { id: 'bundesliga_2_DAR', name: 'SV Darmstadt 98', abbr: 'DAR', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/DAR.png' },
      { id: 'bundesliga_2_DUS', name: 'Fortuna Düsseldorf', abbr: 'DUS', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/DUS.png' },
      { id: 'bundesliga_2_ELV', name: 'SV Elversberg', abbr: 'ELV', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/bundesliga_2/ELV.png' },
      { id: 'bundesliga_2_FUR', name: 'SpVgg Greuther Fürth', abbr: 'FUR', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/FUR.png' },
      { id: 'bundesliga_2_HAM', name: 'Hamburger SV', abbr: 'HAM', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/bundesliga_2/HAM.png' },
      { id: 'bundesliga_2_HAN', name: 'Hannover 96', abbr: 'HAN', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/HAN.png' },
      { id: 'bundesliga_2_KAR', name: 'Karlsruher SC', abbr: 'KAR', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/KAR.png' },
      { id: 'bundesliga_2_KAI', name: 'FC Kaiserslautern', abbr: 'KAI', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/KAI.png' },
      { id: 'bundesliga_2_KOL', name: 'FC Köln', abbr: 'KOL', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/bundesliga_2/KOL.png' },
      { id: 'bundesliga_2_MAG', name: 'FC Magdeburg', abbr: 'MAG', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/MAG.png' },
      { id: 'bundesliga_2_NUR', name: 'FC Nürnberg', abbr: 'NUR', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/NUR.png' },
      { id: 'bundesliga_2_PAD', name: 'SC Paderborn 07', abbr: 'PAD', color1: '#0055A4', color2: '#000000', logo: './assets/logos/bundesliga_2/PAD.png' },
      { id: 'bundesliga_2_PMU', name: 'Preußen Münster', abbr: 'PMU', color1: '#008000', color2: '#000000', logo: './assets/logos/bundesliga_2/PMU.png' },
      { id: 'bundesliga_2_ROS', name: 'Hansa Rostock', abbr: 'ROS', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/ROS.png' },
      { id: 'bundesliga_2_S04', name: 'FC Schalke 04', abbr: 'S04', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/S04.png' },
      { id: 'bundesliga_2_ULM', name: 'SSV Ulm 1846', abbr: 'ULM', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/bundesliga_2/ULM.png' },
    ],
  },
  ligue_1: {
    id: 'ligue_1',
    name: 'Ligue 1',
    continent: 'Avrupa',
    country: 'Fransa',
    teams: [
        { id: 'ligue_1_ANG', name: 'Angers SCO', abbr: 'ANG', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/ligue_1/ANG.png' },
        { id: 'ligue_1_AUX', name: 'AJ Auxerre', abbr: 'AUX', color1: '#FFFFFF', color2: '#006AB2', logo: './assets/logos/ligue_1/AUX.png' },
        { id: 'ligue_1_BRS', name: 'Brest', abbr: 'BRS', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/ligue_1/BRS.png' },
        { id: 'ligue_1_LHV', name: 'Le Havre AC', abbr: 'LHV', color1: '#0A2D6E', color2: '#73C2E8', logo: './assets/logos/ligue_1/LHV.png' },
        { id: 'ligue_1_LEN', name: 'RC Lens', abbr: 'LEN', color1: '#F4D00C', color2: '#D52128', logo: './assets/logos/ligue_1/LEN.png' },
        { id: 'ligue_1_LIL', name: 'Lille OSC', abbr: 'LIL', color1: '#E01E13', color2: '#002855', logo: './assets/logos/ligue_1/LIL.png' },
        { id: 'ligue_1_LYO', name: 'Olympique Lyonnais', abbr: 'LYO', color1: '#FFFFFF', color2: '#0055A4', logo: './assets/logos/ligue_1/LYO.png' },
        { id: 'ligue_1_MAR', name: 'Olympique de Marseille', abbr: 'MAR', color1: '#FFFFFF', color2: '#00BFFF', logo: './assets/logos/ligue_1/MAR.png' },
        { id: 'ligue_1_MON', name: 'AS Monaco', abbr: 'MON', color1: '#ED1B24', color2: '#FFFFFF', logo: './assets/logos/ligue_1/MON.png' },
        { id: 'ligue_1_MHS', name: 'Montpellier HSC', abbr: 'MHS', color1: '#00338D', color2: '#FF6600', logo: './assets/logos/ligue_1/MHS.png' },
        { id: 'ligue_1_NAN', name: 'FC Nantes', abbr: 'NAN', color1: '#FFF200', color2: '#00A651', logo: './assets/logos/ligue_1/NAN.png' },
        { id: 'ligue_1_NIC', name: 'OGC Nice', abbr: 'NIC', color1: '#000000', color2: '#E20A17', logo: './assets/logos/ligue_1/NIC.png' },
        { id: 'ligue_1_PSG', name: 'Paris Saint-Germain', abbr: 'PSG', color1: '#00419B', color2: '#DA291C', logo: './assets/logos/ligue_1/PSG.png' },
        { id: 'ligue_1_REI', name: 'Stade de Reims', abbr: 'REI', color1: '#E20A17', color2: '#FFFFFF', logo: './assets/logos/ligue_1/REI.png' },
        { id: 'ligue_1_REN', name: 'Stade Rennais', abbr: 'REN', color1: '#D52128', color2: '#000000', logo: './assets/logos/ligue_1/REN.png' },
        { id: 'ligue_1_STE', name: 'AS Saint-Étienne', abbr: 'STE', color1: '#008751', color2: '#FFFFFF', logo: './assets/logos/ligue_1/STE.png' },
        { id: 'ligue_1_STR', name: 'RC Strasbourg Alsace', abbr: 'STR', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/ligue_1/STR.png' },
        { id: 'ligue_1_TOU', name: 'Toulouse FC', abbr: 'TOU', color1: '#5D3A93', color2: '#FFFFFF', logo: './assets/logos/ligue_1/TOU.png' },
    ],
  },
  ligue_2: {
    id: 'ligue_2',
    name: 'Ligue 2',
    continent: 'Avrupa',
    country: 'Fransa',
    teams: [
      { id: 'ligue_2_AJA', name: 'AC Ajaccio', abbr: 'AJA', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/ligue_2/AJA.png' },
      { id: 'ligue_2_AMI', name: 'Amiens SC', abbr: 'AMI', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/ligue_2/AMI.png' },
      { id: 'ligue_2_CAE', name: 'SM Caen', abbr: 'CAE', color1: '#0055A4', color2: '#ED1C24', logo: './assets/logos/ligue_2/CAE.png' },
      { id: 'ligue_2_CLE', name: 'Clermont Foot 63', abbr: 'CLE', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/ligue_2/CLE.png' },
      { id: 'ligue_2_CON', name: 'US Concarneau', abbr: 'CON', color1: '#0055A4', color2: '#ED1C24', logo: './assets/logos/ligue_2/CON.png' },
      { id: 'ligue_2_DUN', name: 'USL Dunkerque', abbr: 'DUN', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/ligue_2/DUN.png' },
      { id: 'ligue_2_LOR', name: 'FC Lorient', abbr: 'LOR', color1: '#FF6600', color2: '#000000', logo: './assets/logos/ligue_2/LOR.png' },
      { id: 'ligue_2_GRE', name: 'Grenoble Foot 38', abbr: 'GRE', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/ligue_2/GRE.png' },
      { id: 'ligue_2_GUI', name: 'EA Guingamp', abbr: 'GUI', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/ligue_2/GUI.png' },
      { id: 'ligue_2_LAV', name: 'Stade Lavallois', abbr: 'LAV', color1: '#FF6600', color2: '#000000', logo: './assets/logos/ligue_2/LAV.png' },
      { id: 'ligue_2_MRT', name: 'FC Martigues', abbr: 'MRT', color1: '#FFC72C', color2: '#ED1C24', logo: './assets/logos/ligue_2/MRT.png' },
      { id: 'ligue_2_MET', name: 'FC Metz', abbr: 'MET', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/ligue_2/MET.png' },
      { id: 'ligue_2_PFC', name: 'Paris FC', abbr: 'PFC', color1: '#003366', color2: '#FFFFFF', logo: './assets/logos/ligue_2/PFC.png' },
      { id: 'ligue_2_PAU', name: 'Pau FC', abbr: 'PAU', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/ligue_2/PAU.png' },
      { id: 'ligue_2_RED', name: 'Red Star FC', abbr: 'RED', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/ligue_2/RED.png' },
      { id: 'ligue_2_ROD', name: 'Rodez AF', abbr: 'ROD', color1: '#ED1C24', color2: '#FFC72C', logo: './assets/logos/ligue_2/ROD.png' },
      { id: 'ligue_2_SOC', name: 'FC Sochaux-Montbéliard', abbr: 'SOC', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/ligue_2/SOC.png' },
      { id: 'ligue_2_VAL', name: 'Valenciennes FC', abbr: 'VAL', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/ligue_2/VAL.png' },
    ],
  },
  super_lig: {
    id: 'super_lig',
    name: 'Trendyol Süper Lig',
    continent: 'Avrupa',
    country: 'Türkiye',
    teams: [
        { id: 'super_lig_ADS', name: 'Adana Demirspor', abbr: 'ADS', color1: '#003366', color2: '#418Fde', logo: './assets/logos/super_lig/ADS.png' },
        { id: 'super_lig_ALA', name: 'Alanyaspor', abbr: 'ALA', color1: '#FF6600', color2: '#008000', logo: './assets/logos/super_lig/ALA.png' },
        { id: 'super_lig_ANT', name: 'Antalyaspor', abbr: 'ANT', color1: '#FF0000', color2: '#FFFFFF', logo: './assets/logos/super_lig/ANT.png' },
        { id: 'super_lig_BJK', name: 'Beşiktaş', abbr: 'BJK', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/super_lig/BJK.png' },
        { id: 'super_lig_BOD', name: 'Bodrum FK', abbr: 'BOD', color1: '#009639', color2: '#FFFFFF', logo: './assets/logos/super_lig/BOD.png' },
        { id: 'super_lig_RIZ', name: 'Çaykur Rizespor', abbr: 'RIZ', color1: '#009A44', color2: '#0055A4', logo: './assets/logos/super_lig/RIZ.png' },
        { id: 'super_lig_EYP', name: 'Eyüpspor', abbr: 'EYP', color1: '#5D3A93', color2: '#FFC425', logo: './assets/logos/super_lig/EYP.png' },
        { id: 'super_lig_FB', name: 'Fenerbahçe', abbr: 'FB', color1: '#003366', color2: '#FFCC00', logo: './assets/logos/super_lig/FB.png' },
        { id: 'super_lig_GS', name: 'Galatasaray', abbr: 'GS', color1: '#FDB913', color2: '#A30008', logo: './assets/logos/super_lig/GS.png' },
        { id: 'super_lig_GFK', name: 'Gaziantep FK', abbr: 'GFK', color1: '#DE0000', color2: '#000000', logo: './assets/logos/super_lig/GFK.png' },
        { id: 'super_lig_GOZ', name: 'Göztepe', abbr: 'GOZ', color1: '#FFC107', color2: '#DA291C', logo: './assets/logos/super_lig/GOZ.png' },
        { id: 'super_lig_HAT', name: 'Atakaş Hatayspor', abbr: 'HAT', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/super_lig/HAT.png' },
        { id: 'super_lig_IBFK', name: 'RAMS Başakşehir', abbr: 'İBFK', color1: '#FF6600', color2: '#003366', logo: './assets/logos/super_lig/IBFK.png' },
        { id: 'super_lig_KAS', name: 'Kasımpaşa', abbr: 'KAS', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/super_lig/KAS.png' },
        { id: 'super_lig_KAY', name: 'Kayserispor', abbr: 'KAY', color1: '#FF0000', color2: '#FFFF00', logo: './assets/logos/super_lig/KAY.png' },
        { id: 'super_lig_KON', name: 'Konyaspor', abbr: 'KON', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/super_lig/KON.png' },
        { id: 'super_lig_SAM', name: 'Yılport Samsunspor', abbr: 'SAM', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/super_lig/SAM.png' },
        { id: 'super_lig_SIV', name: 'Sivasspor', abbr: 'SİV', color1: '#FF0000', color2: '#FFFFFF', logo: './assets/logos/super_lig/SIV.png' },
        { id: 'super_lig_TS', name: 'Trabzonspor', abbr: 'TS', color1: '#8B0000', color2: '#87CEEB', logo: './assets/logos/super_lig/TS.png' },
    ],
  },
  tff_1_lig: {
    id: 'tff_1_lig',
    name: 'Trendyol 1. Lig',
    continent: 'Avrupa',
    country: 'Türkiye',
    teams: [
      { id: 'tff_1_lig_AMD', name: 'Amedspor', abbr: 'AMD', color1: '#008000', color2: '#ED1C24', logo: './assets/logos/tff_1_lig/AMD.png' },
      { id: 'tff_1_lig_ANK', name: 'MKE Ankaragücü', abbr: 'ANK', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/tff_1_lig/ANK.png' },
      { id: 'tff_1_lig_BAN', name: 'Teksüt Bandırmaspor', abbr: 'BAN', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/tff_1_lig/BAN.png' },
      { id: 'tff_1_lig_BOL', name: 'Boluspor', abbr: 'BOL', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/tff_1_lig/BOL.png' },
      { id: 'tff_1_lig_COR', name: 'Ahlatcı Çorum FK', abbr: 'COR', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/tff_1_lig/COR.png' },
      { id: 'tff_1_lig_ERZ', name: 'Erzurumspor FK', abbr: 'ERZ', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/tff_1_lig/ERZ.png' },
      { id: 'tff_1_lig_ERO', name: 'Esenler Erokspor', abbr: 'ERO', color1: '#FFC72C', color2: '#008000', logo: './assets/logos/tff_1_lig/ERO.png' },
      { id: 'tff_1_lig_FKG', name: 'Fatih Karagümrük', abbr: 'FKG', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/tff_1_lig/FKG.png' },
      { id: 'tff_1_lig_GEN', name: 'Gençlerbirliği', abbr: 'GEN', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/tff_1_lig/GEN.png' },
      { id: 'tff_1_lig_IGD', name: 'Alagöz Holding Iğdır FK', abbr: 'IGD', color1: '#008000', color2: '#FFC72C', logo: './assets/logos/tff_1_lig/IGD.png' },
      { id: 'tff_1_lig_IST', name: 'İstanbulspor', abbr: 'IST', color1: '#FFC72C', color2: '#000000', logo: './assets/logos/tff_1_lig/IST.png' },
      { id: 'tff_1_lig_KEC', name: 'Ankara Keçiörengücü', abbr: 'KEC', color1: '#5D3A93', color2: '#FFFFFF', logo: './assets/logos/tff_1_lig/KEC.png' },
      { id: 'tff_1_lig_KOC', name: 'Kocaelispor', abbr: 'KOC', color1: '#008000', color2: '#000000', logo: './assets/logos/tff_1_lig/KOC.png' },
      { id: 'tff_1_lig_MAN', name: 'Manisa FK', abbr: 'MAN', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/tff_1_lig/MAN.png' },
      { id: 'tff_1_lig_PEN', name: 'Pendikspor', abbr: 'PEN', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/tff_1_lig/PEN.png' },
      { id: 'tff_1_lig_SAK', name: 'Sakaryaspor', abbr: 'SAK', color1: '#008000', color2: '#000000', logo: './assets/logos/tff_1_lig/SAK.png' },
      { id: 'tff_1_lig_SAN', name: 'Astor Enerji Şanlıurfaspor', abbr: 'SAN', color1: '#FFC72C', color2: '#008000', logo: './assets/logos/tff_1_lig/SAN.png' },
      { id: 'tff_1_lig_UMR', name: 'Ümraniyespor', abbr: 'UMR', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/tff_1_lig/UMR.png' },
      { id: 'tff_1_lig_VAN', name: 'Vanspor FK', abbr: 'VAN', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/tff_1_lig/VAN.png' },
      { id: 'tff_1_lig_YMS', name: 'Yeni Malatyaspor', abbr: 'YMS', color1: '#FFC72C', color2: '#ED1C24', logo: './assets/logos/tff_1_lig/YMS.png' },
    ],
  },
  eredivisie: {
    id: 'eredivisie',
    name: 'Eredivisie',
    continent: 'Avrupa',
    country: 'Hollanda',
    teams: [
      { id: 'eredivisie_AJA', name: 'Ajax', abbr: 'AJA', color1: '#FFFFFF', color2: '#D2122E', logo: './assets/logos/eredivisie/AJA.png' },
      { id: 'eredivisie_AZ', name: 'AZ Alkmaar', abbr: 'AZ', color1: '#D2122E', color2: '#FFFFFF', logo: './assets/logos/eredivisie/AZ.png' },
      { id: 'eredivisie_ALM', name: 'Almere City FC', abbr: 'ALM', color1: '#B80000', color2: '#000000', logo: './assets/logos/eredivisie/ALM.png' },
      { id: 'eredivisie_FEY', name: 'Feyenoord', abbr: 'FEY', color1: '#E30613', color2: '#FFFFFF', logo: './assets/logos/eredivisie/FEY.png' },
      { id: 'eredivisie_FOR', name: 'Fortuna Sittard', abbr: 'FOR', color1: '#FFD700', color2: '#008000', logo: './assets/logos/eredivisie/FOR.png' },
      { id: 'eredivisie_GAE', name: 'Go Ahead Eagles', abbr: 'GAE', color1: '#D2122E', color2: '#FFD700', logo: './assets/logos/eredivisie/GAE.png' },
      { id: 'eredivisie_GRO', name: 'FC Groningen', abbr: 'GRO', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/eredivisie/GRO.png' },
      { id: 'eredivisie_HEE', name: 'SC Heerenveen', abbr: 'HEE', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/eredivisie/HEE.png' },
      { id: 'eredivisie_HER', name: 'Heracles Almelo', abbr: 'HER', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/eredivisie/HER.png' },
      { id: 'eredivisie_NAC', name: 'NAC Breda', abbr: 'NAC', color1: '#FFC72C', color2: '#000000', logo: './assets/logos/eredivisie/NAC.png' },
      { id: 'eredivisie_NEC', name: 'NEC Nijmegen', abbr: 'NEC', color1: '#D2122E', color2: '#008000', logo: './assets/logos/eredivisie/NEC.png' },
      { id: 'eredivisie_PEC', name: 'PEC Zwolle', abbr: 'PEC', color1: '#003366', color2: '#FFFFFF', logo: './assets/logos/eredivisie/PEC.png' },
      { id: 'eredivisie_PSV', name: 'PSV Eindhoven', abbr: 'PSV', color1: '#D2122E', color2: '#FFFFFF', logo: './assets/logos/eredivisie/PSV.png' },
      { id: 'eredivisie_RKC', name: 'RKC Waalwijk', abbr: 'RKC', color1: '#FFD700', color2: '#003366', logo: './assets/logos/eredivisie/RKC.png' },
      { id: 'eredivisie_SPA', name: 'Sparta Rotterdam', abbr: 'SPA', color1: '#D2122E', color2: '#FFFFFF', logo: './assets/logos/eredivisie/SPA.png' },
      { id: 'eredivisie_TWE', name: 'FC Twente', abbr: 'TWE', color1: '#D2122E', color2: '#FFFFFF', logo: './assets/logos/eredivisie/TWE.png' },
      { id: 'eredivisie_UTR', name: 'FC Utrecht', abbr: 'UTR', color1: '#D2122E', color2: '#FFFFFF', logo: './assets/logos/eredivisie/UTR.png' },
      { id: 'eredivisie_WIL', name: 'Willem II', abbr: 'WIL', color1: '#D2122E', color2: '#003366', logo: './assets/logos/eredivisie/WIL.png' },
    ]
  },
  liga_portugal: {
    id: 'liga_portugal',
    name: 'Liga Portugal',
    continent: 'Avrupa',
    country: 'Portekiz',
    teams: [
      { id: 'liga_portugal_AVS', name: 'AVS', abbr: 'AVS', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/AVS.png' },
      { id: 'liga_portugal_BEN', name: 'Benfica', abbr: 'BEN', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/BEN.png' },
      { id: 'liga_portugal_BOA', name: 'Boavista', abbr: 'BOA', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/BOA.png' },
      { id: 'liga_portugal_BRA', name: 'Braga', abbr: 'BRA', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/BRA.png' },
      { id: 'liga_portugal_CAS', name: 'Casa Pia', abbr: 'CAS', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/CAS.png' },
      { id: 'liga_portugal_EST', name: 'Estoril Praia', abbr: 'EST', color1: '#FFF200', color2: '#0055A4', logo: './assets/logos/liga_portugal/EST.png' },
      { id: 'liga_portugal_AMA', name: 'Estrela da Amadora', abbr: 'AMA', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/liga_portugal/AMA.png' },
      { id: 'liga_portugal_FAM', name: 'Famalicão', abbr: 'FAM', color1: '#003366', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/FAM.png' },
      { id: 'liga_portugal_FAR', name: 'Farense', abbr: 'FAR', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/FAR.png' },
      { id: 'liga_portugal_GIL', name: 'Gil Vicente', abbr: 'GIL', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/liga_portugal/GIL.png' },
      { id: 'liga_portugal_MOR', name: 'Moreirense', abbr: 'MOR', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/MOR.png' },
      { id: 'liga_portugal_NAC', name: 'Nacional', abbr: 'NAC', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/NAC.png' },
      { id: 'liga_portugal_POR', name: 'FC Porto', abbr: 'POR', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/POR.png' },
      { id: 'liga_portugal_RIO', name: 'Rio Ave', abbr: 'RIO', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/RIO.png' },
      { id: 'liga_portugal_SCL', name: 'Santa Clara', abbr: 'SCL', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/SCL.png' },
      { id: 'liga_portugal_SCP', name: 'Sporting CP', abbr: 'SCP', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/liga_portugal/SCP.png' },
      { id: 'liga_portugal_VSC', name: 'Vitória de Guimarães', abbr: 'VSC', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/liga_portugal/VSC.png' },
      { id: 'liga_portugal_ARO', name: 'FC Arouca', abbr: 'ARO', color1: '#FFF200', color2: '#003366', logo: './assets/logos/liga_portugal/ARO.png' },
    ]
  },
  jupiler_pro_league: {
    id: 'jupiler_pro_league',
    name: 'Jupiler Pro League',
    continent: 'Avrupa',
    country: 'Belçika',
    teams: [
      { id: 'jupiler_pro_league_AND', name: 'Anderlecht', abbr: 'AND', color1: '#5D3A93', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/AND.png' },
      { id: 'jupiler_pro_league_ANTW', name: 'Royal Antwerp', abbr: 'ANTW', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/ANTW.png' },
      { id: 'jupiler_pro_league_BEE', name: 'Beerschot', abbr: 'BEE', color1: '#5D3A93', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/BEE.png' },
      { id: 'jupiler_pro_league_CER', name: 'Cercle Brugge', abbr: 'CER', color1: '#009A44', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/CER.png' },
      { id: 'jupiler_pro_league_CLU', name: 'Club Brugge', abbr: 'CLU', color1: '#0055A4', color2: '#000000', logo: './assets/logos/jupiler_pro_league/CLU.png' },
      { id: 'jupiler_pro_league_CHA', name: 'Charleroi', abbr: 'CHA', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/CHA.png' },
      { id: 'jupiler_pro_league_DEN', name: 'Dender', abbr: 'DEN', color1: '#0055A4', color2: '#000000', logo: './assets/logos/jupiler_pro_league/DEN.png' },
      { id: 'jupiler_pro_league_GNK', name: 'KRC Genk', abbr: 'GNK', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/GNK.png' },
      { id: 'jupiler_pro_league_GNT', name: 'KAA Gent', abbr: 'GNT', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/GNT.png' },
      { id: 'jupiler_pro_league_KVK', name: 'KV Kortrijk', abbr: 'KVK', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/KVK.png' },
      { id: 'jupiler_pro_league_KVM', name: 'KV Mechelen', abbr: 'KVM', color1: '#FFF200', color2: '#ED1C24', logo: './assets/logos/jupiler_pro_league/KVM.png' },
      { id: 'jupiler_pro_league_OHL', name: 'Oud-Heverlee Leuven', abbr: 'OHL', color1: '#FFFFFF', color2: '#009A44', logo: './assets/logos/jupiler_pro_league/OHL.png' },
      { id: 'jupiler_pro_league_STV', name: 'Sint-Truidense', abbr: 'STV', color1: '#FFF200', color2: '#0055A4', logo: './assets/logos/jupiler_pro_league/STV.png' },
      { id: 'jupiler_pro_league_STA', name: 'Standard Liège', abbr: 'STA', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/jupiler_pro_league/STA.png' },
      { id: 'jupiler_pro_league_USG', name: 'Union Saint-Gilloise', abbr: 'USG', color1: '#FFF200', color2: '#0055A4', logo: './assets/logos/jupiler_pro_league/USG.png' },
      { id: 'jupiler_pro_league_WES', name: 'Westerlo', abbr: 'WES', color1: '#FFF200', color2: '#0055A4', logo: './assets/logos/jupiler_pro_league/WES.png' },
    ]
  },
  scottish_premiership: {
    id: 'scottish_premiership',
    name: 'Scottish Premiership',
    continent: 'Avrupa',
    country: 'İskoçya',
    teams: [
      { id: 'scottish_premiership_ABE', name: 'Aberdeen', abbr: 'ABE', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/ABE.png' },
      { id: 'scottish_premiership_CEL', name: 'Celtic', abbr: 'CEL', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/CEL.png' },
      { id: 'scottish_premiership_DFC', name: 'Dundee FC', abbr: 'DFC', color1: '#003366', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/DFC.png' },
      { id: 'scottish_premiership_DUND', name: 'Dundee United', abbr: 'DUND', color1: '#FF6600', color2: '#000000', logo: './assets/logos/scottish_premiership/DUND.png' },
      { id: 'scottish_premiership_HEA', name: 'Heart of Midlothian', abbr: 'HEA', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/HEA.png' },
      { id: 'scottish_premiership_HIB', name: 'Hibernian', abbr: 'HIB', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/HIB.png' },
      { id: 'scottish_premiership_KIL', name: 'Kilmarnock', abbr: 'KIL', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/KIL.png' },
      { id: 'scottish_premiership_MOT', name: 'Motherwell', abbr: 'MOT', color1: '#8A1E2A', color2: '#FFC72C', logo: './assets/logos/scottish_premiership/MOT.png' },
      { id: 'scottish_premiership_RAN', name: 'Rangers', abbr: 'RAN', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/RAN.png' },
      { id: 'scottish_premiership_ROS', name: 'Ross County', abbr: 'ROS', color1: '#003366', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/ROS.png' },
      { id: 'scottish_premiership_STJ', name: 'St. Johnstone', abbr: 'STJ', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/STJ.png' },
      { id: 'scottish_premiership_STM', name: 'St. Mirren', abbr: 'STM', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/scottish_premiership/STM.png' },
    ]
  },
  brasileirao: {
    id: 'brasileirao',
    name: 'Brasileirão Série A',
    continent: 'Güney Amerika',
    country: 'Brezilya',
    teams: [
      { id: 'brasileirao_ATG', name: 'Atlético Goianiense', abbr: 'ATG', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/brasileirao/ATG.png' },
      { id: 'brasileirao_CAM', name: 'Atlético Mineiro', abbr: 'CAM', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/brasileirao/CAM.png' },
      { id: 'brasileirao_ATP', name: 'Athletico Paranaense', abbr: 'ATP', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/brasileirao/ATP.png' },
      { id: 'brasileirao_BAH', name: 'Bahia', abbr: 'BAH', color1: '#0055A4', color2: '#ED1C24', logo: './assets/logos/brasileirao/BAH.png' },
      { id: 'brasileirao_BOT', name: 'Botafogo', abbr: 'BOT', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/brasileirao/BOT.png' },
      { id: 'brasileirao_RBB', name: 'Red Bull Bragantino', abbr: 'RBB', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/brasileirao/RBB.png' },
      { id: 'brasileirao_COR', name: 'Corinthians', abbr: 'COR', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/brasileirao/COR.png' },
      { id: 'brasileirao_CRI', name: 'Criciúma', abbr: 'CRI', color1: '#FFC72C', color2: '#000000', logo: './assets/logos/brasileirao/CRI.png' },
      { id: 'brasileirao_CRU', name: 'Cruzeiro', abbr: 'CRU', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/brasileirao/CRU.png' },
      { id: 'brasileirao_CUI', name: 'Cuiabá', abbr: 'CUI', color1: '#00A651', color2: '#FFC72C', logo: './assets/logos/brasileirao/CUI.png' },
      { id: 'brasileirao_FLA', name: 'Flamengo', abbr: 'FLA', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/brasileirao/FLA.png' },
      { id: 'brasileirao_FLU', name: 'Fluminense', abbr: 'FLU', color1: '#8A1E2A', color2: '#00A651', logo: './assets/logos/brasileirao/FLU.png' },
      { id: 'brasileirao_FOR', name: 'Fortaleza', abbr: 'FOR', color1: '#0055A4', color2: '#ED1C24', logo: './assets/logos/brasileirao/FOR.png' },
      { id: 'brasileirao_GRE', name: 'Grêmio', abbr: 'GRE', color1: '#0055A4', color2: '#000000', logo: './assets/logos/brasileirao/GRE.png' },
      { id: 'brasileirao_INTER', name: 'Internacional', abbr: 'INTER', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/brasileirao/INTER.png' },
      { id: 'brasileirao_JUV', name: 'Juventude', abbr: 'JUV', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/brasileirao/JUV.png' },
      { id: 'brasileirao_PAL', name: 'Palmeiras', abbr: 'PAL', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/brasileirao/PAL.png' },
      { id: 'brasileirao_SAO', name: 'São Paulo', abbr: 'SAO', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/brasileirao/SAO.png' },
      { id: 'brasileirao_VAS', name: 'Vasco da Gama', abbr: 'VAS', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/brasileirao/VAS.png' },
      { id: 'brasileirao_VIT', name: 'Vitória', abbr: 'VIT', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/brasileirao/VIT.png' },
    ]
  },
  brasileirao_b: {
    id: 'brasileirao_b',
    name: 'Brasileirão Série B',
    continent: 'Güney Amerika',
    country: 'Brezilya',
    teams: [
      { id: 'brasileirao_b_AMZ', name: 'Amazonas', abbr: 'AMZ', color1: '#FFC72C', color2: '#000000', logo: './assets/logos/brasileirao_b/AMZ.png' },
      { id: 'brasileirao_b_AMG', name: 'América-MG', abbr: 'AMG', color1: '#008000', color2: '#000000', logo: './assets/logos/brasileirao_b/AMG.png' },
      { id: 'brasileirao_b_AVA', name: 'Avaí', abbr: 'AVA', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/AVA.png' },
      { id: 'brasileirao_b_BSP', name: 'Botafogo-SP', abbr: 'BSP', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/BSP.png' },
      { id: 'brasileirao_b_BRU', name: 'Brusque', abbr: 'BRU', color1: '#FFC72C', color2: '#008000', logo: './assets/logos/brasileirao_b/BRU.png' },
      { id: 'brasileirao_b_CEA', name: 'Ceará', abbr: 'CEA', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/CEA.png' },
      { id: 'brasileirao_b_CHA', name: 'Chapecoense', abbr: 'CHA', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/CHA.png' },
      { id: 'brasileirao_b_CTB', name: 'Coritiba', abbr: 'CTB', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/CTB.png' },
      { id: 'brasileirao_b_CRB', name: 'CRB', abbr: 'CRB', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/CRB.png' },
      { id: 'brasileirao_b_GOI', name: 'Goiás', abbr: 'GOI', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/GOI.png' },
      { id: 'brasileirao_b_GUA', name: 'Guarani', abbr: 'GUA', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/GUA.png' },
      { id: 'brasileirao_b_ITU', name: 'Ituano', abbr: 'ITU', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/brasileirao_b/ITU.png' },
      { id: 'brasileirao_b_MIR', name: 'Mirassol', abbr: 'MIR', color1: '#FFC72C', color2: '#008000', logo: './assets/logos/brasileirao_b/MIR.png' },
      { id: 'brasileirao_b_NOV', name: 'Novorizontino', abbr: 'NOV', color1: '#FFC72C', color2: '#000000', logo: './assets/logos/brasileirao_b/NOV.png' },
      { id: 'brasileirao_b_OPE', name: 'Operário-PR', abbr: 'OPE', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/OPE.png' },
      { id: 'brasileirao_b_PAY', name: 'Paysandu', abbr: 'PAY', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/PAY.png' },
      { id: 'brasileirao_b_PON', name: 'Ponte Preta', abbr: 'PON', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/brasileirao_b/PON.png' },
      { id: 'brasileirao_b_SAN', name: 'Santos', abbr: 'SAN', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/brasileirao_b/SAN.png' },
      { id: 'brasileirao_b_SPO', name: 'Sport Recife', abbr: 'SPO', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/brasileirao_b/SPO.png' },
      { id: 'brasileirao_b_VIL', name: 'Vila Nova', abbr: 'VIL', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/brasileirao_b/VIL.png' },
    ],
  },
  liga_profesional_ar: {
    id: 'liga_profesional_ar',
    name: 'Liga Profesional de Fútbol',
    continent: 'Güney Amerika',
    country: 'Arjantin',
    teams: [
      { id: 'liga_profesional_ar_ARG', name: 'Argentinos Juniors', abbr: 'ARG', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/ARG.png' },
      { id: 'liga_profesional_ar_ATU', name: 'Atlético Tucumán', abbr: 'ATU', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/ATU.png' },
      { id: 'liga_profesional_ar_BAN', name: 'Banfield', abbr: 'BAN', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/BAN.png' },
      { id: 'liga_profesional_ar_BARC', name: 'Barracas Central', abbr: 'BARC', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/BARC.png' },
      { id: 'liga_profesional_ar_BEL', name: 'Belgrano', abbr: 'BEL', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/BEL.png' },
      { id: 'liga_profesional_ar_BOC', name: 'Boca Juniors', abbr: 'BOC', color1: '#0055A4', color2: '#FFC72C', logo: './assets/logos/liga_profesional_ar/BOC.png' },
      { id: 'liga_profesional_ar_CCE', name: 'Central Córdoba (SdE)', abbr: 'CCE', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/CCE.png' },
      { id: 'liga_profesional_ar_DEF', name: 'Defensa y Justicia', abbr: 'DEF', color1: '#00A651', color2: '#FFC72C', logo: './assets/logos/liga_profesional_ar/DEF.png' },
      { id: 'liga_profesional_ar_RIE', name: 'Deportivo Riestra', abbr: 'RIE', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/RIE.png' },
      { id: 'liga_profesional_ar_EST', name: 'Estudiantes (LP)', abbr: 'EST', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/EST.png' },
      { id: 'liga_profesional_ar_GIM', name: 'Gimnasia (LP)', abbr: 'GIM', color1: '#FFFFFF', color2: '#003366', logo: './assets/logos/liga_profesional_ar/GIM.png' },
      { id: 'liga_profesional_ar_GOD', name: 'Godoy Cruz', abbr: 'GOD', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/GOD.png' },
      { id: 'liga_profesional_ar_HUR', name: 'Huracán', abbr: 'HUR', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/liga_profesional_ar/HUR.png' },
      { id: 'liga_profesional_ar_IND', name: 'Independiente', abbr: 'IND', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/IND.png' },
      { id: 'liga_profesional_ar_INDR', name: 'Independiente Rivadavia', abbr: 'INDR', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/INDR.png' },
      { id: 'liga_profesional_ar_INS', name: 'Instituto', abbr: 'INS', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/INS.png' },
      { id: 'liga_profesional_ar_LAN', name: 'Lanús', abbr: 'LAN', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/LAN.png' },
      { id: 'liga_profesional_ar_NEW', name: 'Newell\'s Old Boys', abbr: 'NEW', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/liga_profesional_ar/NEW.png' },
      { id: 'liga_profesional_ar_PLA', name: 'Platense', abbr: 'PLA', color1: '#8A1E2A', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/PLA.png' },
      { id: 'liga_profesional_ar_RAC', name: 'Racing Club', abbr: 'RAC', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/RAC.png' },
      { id: 'liga_profesional_ar_RIV', name: 'River Plate', abbr: 'RIV', color1: '#FFFFFF', color2: '#ED1C24', logo: './assets/logos/liga_profesional_ar/RIV.png' },
      { id: 'liga_profesional_ar_ROS', name: 'Rosario Central', abbr: 'ROS', color1: '#0055A4', color2: '#FFC72C', logo: './assets/logos/liga_profesional_ar/ROS.png' },
      { id: 'liga_profesional_ar_SAN', name: 'San Lorenzo', abbr: 'SAN', color1: '#0055A4', color2: '#ED1C24', logo: './assets/logos/liga_profesional_ar/SAN.png' },
      { id: 'liga_profesional_ar_SAR', name: 'Sarmiento', abbr: 'SAR', color1: '#00A651', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/SAR.png' },
      { id: 'liga_profesional_ar_TAL', name: 'Talleres (C)', abbr: 'TAL', color1: '#003366', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/TAL.png' },
      { id: 'liga_profesional_ar_TIG', name: 'Tigre', abbr: 'TIG', color1: '#0055A4', color2: '#ED1C24', logo: './assets/logos/liga_profesional_ar/TIG.png' },
      { id: 'liga_profesional_ar_UNI', name: 'Unión', abbr: 'UNI', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/liga_profesional_ar/UNI.png' },
      { id: 'liga_profesional_ar_VEL', name: 'Vélez Sarsfield', abbr: 'VEL', color1: '#FFFFFF', color2: '#0055A4', logo: './assets/logos/liga_profesional_ar/VEL.png' },
    ]
  },
  primera_nacional_ar: {
    id: 'primera_nacional_ar',
    name: 'Primera Nacional',
    continent: 'Güney Amerika',
    country: 'Arjantin',
    teams: [
      { id: 'primera_nacional_ar_ALL', name: 'All Boys', abbr: 'ALL', color1: '#FFFFFF', color2: '#000000', logo: './assets/logos/primera_nacional_ar/ALL.png' },
      { id: 'primera_nacional_ar_ALM', name: 'Almirante Brown', abbr: 'ALM', color1: '#FFC72C', color2: '#000000', logo: './assets/logos/primera_nacional_ar/ALM.png' },
      { id: 'primera_nacional_ar_ALD', name: 'Aldosivi', abbr: 'ALD', color1: '#008000', color2: '#FFC72C', logo: './assets/logos/primera_nacional_ar/ALD.png' },
      { id: 'primera_nacional_ar_ATR', name: 'Atlético de Rafaela', abbr: 'ATR', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/ATR.png' },
      { id: 'primera_nacional_ar_CHA', name: 'Chacarita Juniors', abbr: 'CHA', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/primera_nacional_ar/CHA.png' },
      { id: 'primera_nacional_ar_COL', name: 'Colón', abbr: 'COL', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/primera_nacional_ar/COL.png' },
      { id: 'primera_nacional_ar_DFB', name: 'Defensores de Belgrano', abbr: 'DFB', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/primera_nacional_ar/DFB.png' },
      { id: 'primera_nacional_ar_MOR', name: 'Deportivo Morón', abbr: 'MOR', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/MOR.png' },
      { id: 'primera_nacional_ar_FER', name: 'Ferro Carril Oeste', abbr: 'FER', color1: '#008000', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/FER.png' },
      { id: 'primera_nacional_ar_GIMJ', name: 'Gimnasia y Esgrima (Jujuy)', abbr: 'GIMJ', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/GIMJ.png' },
      { id: 'primera_nacional_ar_GIMM', name: 'Gimnasia y Esgrima (Mendoza)', abbr: 'GIMM', color1: '#000000', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/GIMM.png' },
      { id: 'primera_nacional_ar_NUE', name: 'Nueva Chicago', abbr: 'NUE', color1: '#008000', color2: '#000000', logo: './assets/logos/primera_nacional_ar/NUE.png' },
      { id: 'primera_nacional_ar_PAT', name: 'Patronato', abbr: 'PAT', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/primera_nacional_ar/PAT.png' },
      { id: 'primera_nacional_ar_QUI', name: 'Quilmes', abbr: 'QUI', color1: '#FFFFFF', color2: '#0055A4', logo: './assets/logos/primera_nacional_ar/QUI.png' },
      { id: 'primera_nacional_ar_SMSJ', name: 'San Martín (San Juan)', abbr: 'SMSJ', color1: '#008000', color2: '#000000', logo: './assets/logos/primera_nacional_ar/SMSJ.png' },
      { id: 'primera_nacional_ar_SMT', name: 'San Martín (Tucumán)', abbr: 'SMT', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/SMT.png' },
      { id: 'primera_nacional_ar_TEL', name: 'San Telmo', abbr: 'TEL', color1: '#87CEEB', color2: '#003366', logo: './assets/logos/primera_nacional_ar/TEL.png' },
      { id: 'primera_nacional_ar_TEM', name: 'Temperley', abbr: 'TEM', color1: '#87CEEB', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/TEM.png' },
      { id: 'primera_nacional_ar_TRI', name: 'Tristán Suárez', abbr: 'TRI', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/primera_nacional_ar/TRI.png' },
      { id: 'primera_nacional_ar_ATL', name: 'Club Atlético Atlanta', abbr: 'ATL', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/primera_nacional_ar/ATL.png' },
    ],
  },
  mls: {
    id: 'mls',
    name: 'Major League Soccer',
    continent: 'Kuzey Amerika',
    country: 'ABD & Kanada',
    teams: [
      { id: 'mls_ATL', name: 'Atlanta United FC', abbr: 'ATL', color1: '#8A1E2A', color2: '#000000', logo: './assets/logos/mls/ATL.png' },
      { id: 'mls_AUS', name: 'Austin FC', abbr: 'AUS', color1: '#00A651', color2: '#000000', logo: './assets/logos/mls/AUS.png' },
      { id: 'mls_CLT', name: 'Charlotte FC', abbr: 'CLT', color1: '#00A651', color2: '#000000', logo: './assets/logos/mls/CLT.png' },
      { id: 'mls_CHI', name: 'Chicago Fire FC', abbr: 'CHI', color1: '#003366', color2: '#ED1C24', logo: './assets/logos/mls/CHI.png' },
      { id: 'mls_CIN', name: 'FC Cincinnati', abbr: 'CIN', color1: '#0055A4', color2: '#FF6600', logo: './assets/logos/mls/CIN.png' },
      { id: 'mls_COL', name: 'Colorado Rapids', abbr: 'COL', color1: '#8A1E2A', color2: '#87CEEB', logo: './assets/logos/mls/COL.png' },
      { id: 'mls_CLB', name: 'Columbus Crew', abbr: 'CLB', color1: '#FFC72C', color2: '#000000', logo: './assets/logos/mls/CLB.png' },
      { id: 'mls_DAL', name: 'FC Dallas', abbr: 'DAL', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/mls/DAL.png' },
      { id: 'mls_DCU', name: 'D.C. United', abbr: 'DCU', color1: '#000000', color2: '#ED1C24', logo: './assets/logos/mls/DCU.png' },
      { id: 'mls_HOU', name: 'Houston Dynamo FC', abbr: 'HOU', color1: '#FF6600', color2: '#000000', logo: './assets/logos/mls/HOU.png' },
      { id: 'mls_SKC', name: 'Sporting Kansas City', abbr: 'SKC', color1: '#87CEEB', color2: '#003366', logo: './assets/logos/mls/SKC.png' },
      { id: 'mls_LAG', name: 'LA Galaxy', abbr: 'LAG', color1: '#FFFFFF', color2: '#003366', logo: './assets/logos/mls/LAG.png' },
      { id: 'mls_LAFC', name: 'Los Angeles FC', abbr: 'LAFC', color1: '#000000', color2: '#FFC72C', logo: './assets/logos/mls/LAFC.png' },
      { id: 'mls_MIA', name: 'Inter Miami CF', abbr: 'MIA', color1: '#F7B5CD', color2: '#000000', logo: './assets/logos/mls/MIA.png' },
      { id: 'mls_MIN', name: 'Minnesota United FC', abbr: 'MIN', color1: '#87CEEB', color2: '#000000', logo: './assets/logos/mls/MIN.png' },
      { id: 'mls_MTL', name: 'CF Montréal', abbr: 'MTL', color1: '#0055A4', color2: '#000000', logo: './assets/logos/mls/MTL.png' },
      { id: 'mls_NSH', name: 'Nashville SC', abbr: 'NSH', color1: '#FFC72C', color2: '#003366', logo: './assets/logos/mls/NSH.png' },
      { id: 'mls_NER', name: 'New England Revolution', abbr: 'NER', color1: '#003366', color2: '#ED1C24', logo: './assets/logos/mls/NER.png' },
      { id: 'mls_NYC', name: 'New York City FC', abbr: 'NYC', color1: '#87CEEB', color2: '#003366', logo: './assets/logos/mls/NYC.png' },
      { id: 'mls_NYR', name: 'New York Red Bulls', abbr: 'NYR', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/mls/NYR.png' },
      { id: 'mls_ORL', name: 'Orlando City SC', abbr: 'ORL', color1: '#5D3A93', color2: '#FFC72C', logo: './assets/logos/mls/ORL.png' },
      { id: 'mls_PHI', name: 'Philadelphia Union', abbr: 'PHI', color1: '#003366', color2: '#FFC72C', logo: './assets/logos/mls/PHI.png' },
      { id: 'mls_POR', name: 'Portland Timbers', abbr: 'POR', color1: '#00A651', color2: '#FFC72C', logo: './assets/logos/mls/POR.png' },
      { id: 'mls_RSL', name: 'Real Salt Lake', abbr: 'RSL', color1: '#8A1E2A', color2: '#003366', logo: './assets/logos/mls/RSL.png' },
      { id: 'mls_SJE', name: 'San Jose Earthquakes', abbr: 'SJE', color1: '#000000', color2: '#0055A4', logo: './assets/logos/mls/SJE.png' },
      { id: 'mls_SEA', name: 'Seattle Sounders FC', abbr: 'SEA', color1: '#00A651', color2: '#0055A4', logo: './assets/logos/mls/SEA.png' },
      { id: 'mls_STL', name: 'St. Louis City SC', abbr: 'STL', color1: '#ED1C24', color2: '#003366', logo: './assets/logos/mls/STL.png' },
      { id: 'mls_TOR', name: 'Toronto FC', abbr: 'TOR', color1: '#ED1C24', color2: '#A9A9A9', logo: './assets/logos/mls/TOR.png' },
      { id: 'mls_VAN', name: 'Vancouver Whitecaps FC', abbr: 'VAN', color1: '#FFFFFF', color2: '#0055A4', logo: './assets/logos/mls/VAN.png' },
    ]
  },
  usl_championship: {
    id: 'usl_championship',
    name: 'USL Championship',
    continent: 'Kuzey Amerika',
    country: 'ABD & Kanada',
    teams: [
      { id: 'usl_championship_BIR', name: 'Birmingham Legion FC', abbr: 'BIR', color1: '#B3202E', color2: '#FFFFFF', logo: './assets/logos/usl_championship/BIR.png' },
      { id: 'usl_championship_CHA', name: 'Charleston Battery', abbr: 'CHA', color1: '#FFD700', color2: '#000000', logo: './assets/logos/usl_championship/CHA.png' },
      { id: 'usl_championship_COS', name: 'Colorado Springs Switchbacks FC', abbr: 'COS', color1: '#0055A4', color2: '#FFFFFF', logo: './assets/logos/usl_championship/COS.png' },
      { id: 'usl_championship_DET', name: 'Detroit City FC', abbr: 'DET', color1: '#8A1E2A', color2: '#FFD700', logo: './assets/logos/usl_championship/DET.png' },
      { id: 'usl_championship_ELP', name: 'El Paso Locomotive FC', abbr: 'ELP', color1: '#003366', color2: '#87CEEB', logo: './assets/logos/usl_championship/ELP.png' },
      { id: 'usl_championship_HAR', name: 'Hartford Athletic', abbr: 'HAR', color1: '#008000', color2: '#0055A4', logo: './assets/logos/usl_championship/HAR.png' },
      { id: 'usl_championship_IND', name: 'Indy Eleven', abbr: 'IND', color1: '#003366', color2: '#ED1C24', logo: './assets/logos/usl_championship/IND.png' },
      { id: 'usl_championship_LVL', name: 'Las Vegas Lights FC', abbr: 'LVL', color1: '#FFC0CB', color2: '#00BFFF', logo: './assets/logos/usl_championship/LVL.png' },
      { id: 'usl_championship_LOU', name: 'Loudoun United FC', abbr: 'LOU', color1: '#ED1C24', color2: '#FFFFFF', logo: './assets/logos/usl_championship/LOU.png' },
      { id: 'usl_championship_LVC', name: 'Louisville City FC', abbr: 'LVC', color1: '#5D3A93', color2: '#FFD700', logo: './assets/logos/usl_championship/LVC.png' },
      { id: 'usl_championship_MEM', name: 'Memphis 901 FC', abbr: 'MEM', color1: '#0055A4', color2: '#FFD700', logo: './assets/logos/usl_championship/MEM.png' },
      { id: 'usl_championship_MIA', name: 'Miami FC', abbr: 'MIA', color1: '#00BFFF', color2: '#FF6600', logo: './assets/logos/usl_championship/MIA.png' },
      { id: 'usl_championship_MON', name: 'Monterey Bay F.C.', abbr: 'MON', color1: '#87CEEB', color2: '#003366', logo: './assets/logos/usl_championship/MON.png' },
      { id: 'usl_championship_NMU', name: 'New Mexico United', abbr: 'NMU', color1: '#FFD700', color2: '#000000', logo: './assets/logos/usl_championship/NMU.png' },
      { id: 'usl_championship_NCF', name: 'North Carolina FC', abbr: 'NCF', color1: '#003366', color2: '#FFD700', logo: './assets/logos/usl_championship/NCF.png' },
      { id: 'usl_championship_OAK', name: 'Oakland Roots SC', abbr: 'OAK', color1: '#000000', color2: '#008000', logo: './assets/logos/usl_championship/OAK.png' },
      { id: 'usl_championship_OC', name: 'Orange County SC', abbr: 'OC', color1: '#FF6600', color2: '#000000', logo: './assets/logos/usl_championship/OC.png' },
      { id: 'usl_championship_PHX', name: 'Phoenix Rising FC', abbr: 'PHX', color1: '#ED1C24', color2: '#000000', logo: './assets/logos/usl_championship/PHX.png' },
      { id: 'usl_championship_PIT', name: 'Pittsburgh Riverhounds SC', abbr: 'PIT', color1: '#000000', color2: '#FFD700', logo: './assets/logos/usl_championship/PIT.png' },
      { id: 'usl_championship_RI', name: 'Rhode Island FC', abbr: 'RI', color1: '#0055A4', color2: '#87CEEB', logo: './assets/logos/usl_championship/RI.png' },
      { id: 'usl_championship_SAC', name: 'Sacramento Republic FC', abbr: 'SAC', color1: '#8A1E2A', color2: '#A9A9A9', logo: './assets/logos/usl_championship/SAC.png' },
      { id: 'usl_championship_SA', name: 'San Antonio FC', abbr: 'SA', color1: '#000000', color2: '#A9A9A9', logo: './assets/logos/usl_championship/SA.png' },
      { id: 'usl_championship_TB', name: 'Tampa Bay Rowdies', abbr: 'TB', color1: '#008000', color2: '#FFD700', logo: './assets/logos/usl_championship/TB.png' },
      { id: 'usl_championship_TUL', name: 'FC Tulsa', abbr: 'TUL', color1: '#FFD700', color2: '#000000', logo: './assets/logos/usl_championship/TUL.png' },
    ],
  },
};

export const TOURNAMENTS: { [key: string]: { id: string, name: string, country: string, leagueIds: string[] } } = {
  ztk: { id: 'ztk', name: 'Ziraat Türkiye Kupası', country: 'Türkiye', leagueIds: ['super_lig', 'tff_1_lig'] },
  fa_cup: { id: 'fa_cup', name: 'FA Cup', country: 'İngiltere', leagueIds: ['premier_lig', 'efl_championship'] },
  copa_del_rey: { id: 'copa_del_rey', name: 'Copa del Rey', country: 'İspanya', leagueIds: ['la_liga', 'la_liga_2'] },
  dfb_pokal: { id: 'dfb_pokal', name: 'DFB-Pokal', country: 'Almanya', leagueIds: ['bundesliga', 'bundesliga_2'] },
  coppa_italia: { id: 'coppa_italia', name: 'Coppa Italia', country: 'İtalya', leagueIds: ['serie_a', 'serie_b_it'] },
  coupe_de_france: { id: 'coupe_de_france', name: 'Coupe de France', country: 'Fransa', leagueIds: ['ligue_1', 'ligue_2'] },
  knvb_cup: { id: 'knvb_cup', name: 'KNVB Cup', country: 'Hollanda', leagueIds: ['eredivisie'] },
  taca_de_portugal: { id: 'taca_de_portugal', name: 'Taça de Portugal', country: 'Portekiz', leagueIds: ['liga_portugal'] },
  belgian_cup: { id: 'belgian_cup', name: 'Belgian Cup', country: 'Belçika', leagueIds: ['jupiler_pro_league'] },
  scottish_cup: { id: 'scottish_cup', name: 'Scottish Cup', country: 'İskoçya', leagueIds: ['scottish_premiership'] },
  copa_do_brasil: { id: 'copa_do_brasil', name: 'Copa do Brasil', country: 'Brezilya', leagueIds: ['brasileirao', 'brasileirao_b'] },
  copa_de_la_liga: { id: 'copa_de_la_liga', name: 'Copa de la Liga', country: 'Arjantin', leagueIds: ['liga_profesional_ar', 'primera_nacional_ar'] },
  mls_cup: { id: 'mls_cup', name: 'MLS Cup', country: 'ABD & Kanada', leagueIds: ['mls', 'usl_championship'] }
};

export const DIFFICULTY_LEVELS: { id: Difficulty, labelKey: string }[] = [
    { id: 'very-easy', labelKey: 'difficulty_very-easy' },
    { id: 'easy', labelKey: 'difficulty_easy' },
    { id: 'normal', labelKey: 'difficulty_normal' },
    { id: 'hard', labelKey: 'difficulty_hard' },
    { id: 'very-hard', labelKey: 'difficulty_very-hard' },
    { id: 'impossible', labelKey: 'difficulty_impossible' },
];

export const GAME_DURATION = 90;
export const HALF_TIME = 45;

export const AI_SPEED_MULTIPLIERS: { [key in Difficulty]: number } = {
    'very-easy': 0.025,
    'easy': 0.04,
    'normal': 0.06,
    'hard': 0.08,
    'very-hard': 0.095,
    'impossible': 0.11,
};

export const SUPPORTED_LANGUAGES: { id: LanguageCode, label: string }[] = [
    { id: 'en', label: 'English' },
    { id: 'tr', label: 'Türkçe' },
    { id: 'es', label: 'Español' },
    { id: 'de', label: 'Deutsch' },
    { id: 'fr', label: 'Français' },
    { id: 'zh', label: '中文' },
    { id: 'hi', label: 'हिन्दी' },
    { id: 'ar', label: 'العربية' },
    { id: 'bn', label: 'বাংলা' },
    { id: 'ru', label: 'Русский' },
    { id: 'pt', label: 'Português' },
    { id: 'ur', label: 'اردو' },
    { id: 'id', label: 'Bahasa Indonesia' },
    { id: 'ja', label: '日本語' },
    { id: 'pcm', label: 'Nigerian Pidgin' },
    { id: 'mr', label: 'मराठी' },
    { id: 'te', label: 'తెలుగు' },
    { id: 'ta', label: 'தமிழ்' },
    { id: 'yue', label: '粵語' },
    { id: 'vi', label: 'Tiếng Việt' },
];